// This file was automatically generated based on instruction_set.yaml
// Do not modify its content directly

using SigType = SimpleInstruction::SigType;
const auto mi = [](
    std::string name,
    int opcode,
    std::initializer_list<SigType> inputs,
    std::initializer_list<SigType> outputs
) { return InstructionOwner(new SimpleInstruction(name, opcode, inputs, outputs)); };

InstructionOwner instructions[] {
    InstructionOwner(new StackInstruction(0)),
    InstructionOwner(new UnstackInstruction(1)),
    InstructionOwner(new BatchCatInstruction(2)),
    InstructionOwner(new BatchSplitInstruction(3)),
    mi("add", 4, {{DataType::dt_float, false, {std::monostate{}}, false}, {DataType::dt_float, false, {std::monostate{}}, false}}, {{DataType::dt_float, false, {std::monostate{}}, false}}),
    mi("sub", 5, {{DataType::dt_float, false, {std::monostate{}}, false}, {DataType::dt_float, false, {std::monostate{}}, false}}, {{DataType::dt_float, false, {std::monostate{}}, false}}),
    mi("mul", 6, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("product", 7, {{DataType::dt_float, false, {"n"}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("clip_min", 8, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("sqrt", 9, {{DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("square", 10, {{DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("pow", 11, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("uniform_phi", 12, {{DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("uniform_phi_inverse", 13, {{DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("uniform_costheta", 14, {{DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("uniform_costheta_inverse", 15, {{DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("rotate_zy", 16, {{DataType::dt_float, false, {4}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {4}, false}}),
    mi("rotate_zy_inverse", 17, {{DataType::dt_float, false, {4}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {4}, false}}),
    mi("boost", 18, {{DataType::dt_float, false, {4}, false}, {DataType::dt_float, false, {4}, false}}, {{DataType::dt_float, false, {4}, false}}),
    mi("boost_inverse", 19, {{DataType::dt_float, false, {4}, false}, {DataType::dt_float, false, {4}, false}}, {{DataType::dt_float, false, {4}, false}}),
    mi("boost_beam", 20, {{DataType::dt_float, false, {"n", 4}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {"n", 4}, false}}),
    mi("boost_beam_inverse", 21, {{DataType::dt_float, false, {"n", 4}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {"n", 4}, false}}),
    mi("com_momentum", 22, {{DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {4}, false}}),
    mi("com_p_in", 23, {{DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {4}, false}, {DataType::dt_float, false, {4}, false}}),
    mi("com_angles", 24, {{DataType::dt_float, false, {4}, false}}, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("s", 25, {{DataType::dt_float, false, {4}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("sqrt_s", 26, {{DataType::dt_float, false, {4}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("s_and_sqrt_s", 27, {{DataType::dt_float, false, {4}, false}}, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("r_to_x1x2", 28, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("x1x2_to_r", 29, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("rapidity", 30, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("decay_momentum", 31, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {4}, false}, {DataType::dt_float, false, {}, false}}),
    mi("invt_min_max", 32, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("invt_to_costheta", 33, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("costheta_to_invt", 34, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("two_particle_density_inverse", 35, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("tinv_two_particle_density", 36, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("tinv_two_particle_density_inverse", 37, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("uniform_invariant", 38, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("uniform_invariant_inverse", 39, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("breit_wigner_invariant", 40, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("breit_wigner_invariant_inverse", 41, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("stable_invariant", 42, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("stable_invariant_inverse", 43, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("stable_invariant_nu", 44, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("stable_invariant_nu_inverse", 45, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("fast_rambo_r_to_u", 46, {{DataType::dt_float, false, {"n"}, false}}, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, false, {}, false}}),
    mi("rambo_four_vectors_massless", 47, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {"n+1"}, false}, {DataType::dt_float, false, {"n+1"}, false}}, {{DataType::dt_float, false, {"n+1", 4}, false}, {DataType::dt_float, false, {"n+1", 4}, false}}),
    mi("rambo_four_vectors_massive", 48, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {"n+1"}, false}, {DataType::dt_float, false, {"n+1"}, false}, {DataType::dt_float, false, {"n+2"}, false}}, {{DataType::dt_float, false, {"n+1", 4}, false}, {DataType::dt_float, false, {"n+1", 4}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("cut_pt", 49, {{DataType::dt_float, false, {"n", 4}, false}, {DataType::dt_float, true, {"n-2", 2}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("cut_eta", 50, {{DataType::dt_float, false, {"n", 4}, false}, {DataType::dt_float, true, {"n-2", 2}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("cut_dr", 51, {{DataType::dt_float, false, {"n", 4}, false}, {DataType::dt_int, true, {"m", 2}, false}, {DataType::dt_float, true, {"m", 2}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("cut_m_inv", 52, {{DataType::dt_float, false, {"n", 4}, false}, {DataType::dt_int, true, {"m", "k"}, false}, {DataType::dt_float, true, {"m", 2}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("cut_sqrt_s", 53, {{DataType::dt_float, false, {"n", 4}, false}, {DataType::dt_float, true, {2}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("chili_forward", 54, {{DataType::dt_float, false, {"3n-2"}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, false, {"n"}, false}}, {{DataType::dt_float, false, {"n+2"}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("matrix_element", 55, {{DataType::dt_float, false, {"n", 4}, false}, {DataType::dt_int, true, {"m"}, false}, {DataType::dt_int, true, {}, false}, {DataType::dt_int, true, {"c"}, true}}, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {"c"}, false}}),
    mi("pdf", 56, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {}, false}, {DataType::dt_int, false, {}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("matmul", 57, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, true, {"m", "n"}, false}, {DataType::dt_float, true, {"m"}, false}}, {{DataType::dt_float, false, {"m"}, false}}),
    mi("leaky_relu", 58, {{DataType::dt_float, false, {std::monostate{}}, false}}, {{DataType::dt_float, false, {std::monostate{}}, false}}),
    InstructionOwner(new RqsActivationInstruction(59)),
    mi("rqs_find_bin", 60, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, false, {"n", "b"}, false}, {DataType::dt_float, false, {"n", "b"}, false}, {DataType::dt_float, false, {"n", "b+1"}, false}}, {{DataType::dt_float, false, {"n", 6}, false}}),
    mi("rqs_forward", 61, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, false, {"n", 6}, false}}, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, false, {"n"}, false}}),
    mi("rqs_inverse", 62, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, false, {"n", 6}, false}}, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, false, {"n"}, false}}),
    mi("softmax", 63, {{DataType::dt_float, false, {"n"}, false}}, {{DataType::dt_float, false, {"n"}, false}}),
    mi("softmax_prior", 64, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, false, {"n"}, false}}, {{DataType::dt_float, false, {"n"}, false}}),
    mi("sample_discrete", 65, {{DataType::dt_float, false, {}, false}, {DataType::dt_int, true, {}, false}}, {{DataType::dt_int, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("sample_discrete_probs", 66, {{DataType::dt_float, false, {}, false}, {DataType::dt_float, false, {"n"}, false}}, {{DataType::dt_int, false, {}, false}, {DataType::dt_float, false, {}, false}}),
    mi("gather", 67, {{DataType::dt_int, false, {}, false}, {DataType::dt_float, false, {"n"}, false}}, {{DataType::dt_float, false, {}, false}}),
    mi("gather_int", 68, {{DataType::dt_int, false, {}, false}, {DataType::dt_int, false, {"n"}, false}}, {{DataType::dt_int, false, {}, false}}),
    mi("select", 69, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_int, true, {"m"}, false}}, {{DataType::dt_float, false, {"m"}, false}}),
    mi("one_hot", 70, {{DataType::dt_int, false, {}, false}, {DataType::dt_int, true, {"n"}, true}}, {{DataType::dt_float, false, {"n"}, false}}),
    mi("vegas_forward", 71, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, true, {"n", "b"}, false}}, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, false, {}, false}}),
    mi("vegas_inverse", 72, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, true, {"n", "b"}, false}}, {{DataType::dt_float, false, {"n"}, false}, {DataType::dt_float, false, {}, false}}),
};
